Tethys4 upgrade (#24)
* Upgrade for thethys4

Co-authored-by: Michael Souffront <msouff@users.noreply.github.com>
Co-authored-by: Nathan Swain <swainn@users.noreply.github.com>

* Update to Tethys 4

Co-authored-by: Michael Souffront <msouff@users.noreply.github.com>

* code cleanup

* Change getting the app_workspace to a function;
Remove unused packages

Co-authored-by: Michael Souffront <msouff@users.noreply.github.com>
Co-authored-by: Nathan Swain <swainn@users.noreply.github.com>

* Add logic to filter out apps by the Tethys Platform that they support.
Also add an unavailable table to check for apps upon upgrades

Co-authored-by: Michael Souffront <msouff@users.noreply.github.com>

* Modified to check compatible tethys platform version according to the app version.

Co-authored-by: Michael Souffront <msouff@users.noreply.github.com>

* Make style changes, pass flake8 test

* new changes to correct the api/git/install

* Refactoring the run git install main function, renaming gitInstall for github_install,and fixed syncstores for github_install

* updated install.yml

* setup tethys channel layer improved.

* possible solution to "You cannot call this from an async context - use a thread or sync_to_async"

* possible solution for 'AttributeError: module 'tethysapp.app_store.notifications' has no attribute 'continueAfterInstall'

* possible solution for module has no attribute "xxxx"

* let's add a little breakpoint

* added some logs for teh moment

* added possible solution to recognize sudo

* debug commit

* possibel solution for error "Exception inside application: Object of type TethysWorkspace is not JSON serializable"

* possible fiox for "AttributeError: module 'tethysapp.app_store.notifications' has no attribute 'set_custom_settings'"

* possible fix for lost of connection in channel

* possible fix 2 for the lost on signal

* test for the lost of signal

* test if bash script can make it wor

* minor changes2

* bug check3

* check if we pass and log the info

* possible final fix the error is in th supervisord configuration

* possible fix for error AttributeError: module 'tethysapp.app_store.notifications' has no attribute 'clear_cache'

* no need for this it was part of an experiment

* possible replacement of the installation using mamba instead of conda.

* added some extra steps to not point the user that the server is restarting when in reality has started to restart while first running syncstores and collectall commands

* need to import process_branch function for the thredds process to work

* Trigger only when there is a push to the tethysapp_warehouse_release branch

* some changes to not remove the repo and just update it

* change in asdas

* changes to not have tethys_apps again

* added new functions to make it compatible with tethys4 scaffolds

* rewritting of the setup.py now compatible with apps that have been migrated from tethys 3 to 4

* change in the main.yml to have tethysapp instead of rfun

* uncomment update dependecies

* just adding new comments for future reference, and also just changing the email to gromero@aquaveo.com

* small big correction

* adding a better version of email for failure

* getting close, only need to also prompt user to update version not much

* more comments for future

* addition of some sort of validation function to check for existing repos

* check for new versions now, the whole validation function needs to be refactored to be more elegant

* removal of the margin-top at 10%

* small bug to reference the original gitub repo

* margin for button

* added option for new app

* correcting more mistakes of copy pate

* changes, refactoring and notes, not tested yet, probably broken.

* add labels to the json config

* changes to have the custom stores in the app

* more notes and customiztion for the different channels

* extra changes to now load everything from the default conda_channel

* half of the function to change between stores

* some changes and customization for the settings.json

* Update home.html

Removed obsolete note.

---------

Co-authored-by: Michael Souffront <msouff@users.noreply.github.com>
Co-authored-by: Nathan Swain <swainn@users.noreply.github.com>
Co-authored-by: romer8 <gio.busrom@gmail.com>
Co-authored-by: Michael Souffront <17328135+msouff@users.noreply.github.com>